config/routes.rb
Rails.application.routes.draw do
  
  resources :chequeos
  resources :vacunas
  patch '/profiles/:id/edit', to: 'profiles#update'  # Cambié 'profiles/:id' a '/profiles/:id'
  get '/profiles/:id/edit', to: 'profiles#edit', as: 'edit_profile'
  get '/profiles/:id', to: 'profiles#index', as: 'profile'
  get 'profiles/update'
  get 'inicio/index'
  get 'turnos/index'
  get 'authentication/sessions/new'
  resources :turnos
  resources :main
  namespace :authentication, path: '', as: '' do
    resources :users, only: [:new, :create]
    resources :sessions, only: [:new, :create]
  end
  get 'logout', to: 'authentication/sessions#destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "inicio#index"
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :profiles, only: [:index, :edit, :update]
  resources :dogs
  resources :dogs do
    get 'verFichaMedica', on: :member
  end
  
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  belongs_to :dog
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  skip_before_action :protect_pages
  before_action :set_profile
  def index
  end

  def edit
    @profile = User.find(params[:id])
  end

  def update
  @profile = current_user 
  if @profile.update(profile_params)
    # Redirigir a la página /profiles/index
    redirect_to profiles_path, notice: 'Perfil actualizado exitosamente'
  else
    render :edit, status: :unprocessable_entity
  end
  end

  private
  def set_profile
  @profile = current_user
  end

  def profile_params
    params.require(:user).permit(:nombre, :apellido, :email, :dni) # Asegura que solo los campos permitidos se actualicen
  end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/edit.html.erb
<h1>Editar Perfil</h1>
<%= form_with(model: @profile, url: edit_profile_path(@profile), method: :patch, local: true) do |form| %>
    <div class="form-row">
    <div class="form-group col-md-2">
      <%= form.label :nombre %>
      <%= form.text_field :nombre, class: "form-control" %>
    </div>
    <div class="form-group col-md-2">
      <%= form.label :apellido %>
      <%= form.text_field :apellido, class: "form-control" %>
    </div>
    <div class="form-group col-md-3">
      <%= form.label :email %>
      <%= form.email_field :email, class: "form-control" %>
    </div>
    <div class="form-group col-md-2">
      <%= form.label :dni %>
      <%= form.number_field :dni, class: "form-control" %>
    </div>
   </div>
      <div class="form-row">
    <div class="form-group col-md-1.5">
       <%= form.submit "Confirmar los datos", class: "btn btn-success"%>
     </div>
   <div class="form-group col-md-1">
       <%=link_to "Cancelar", profile_path(@profile), {class: "btn btn-danger"}%>
     </div>
  </div>


<% end %>

app/views/profiles/index.html.erb
<h1>Mi Perfil</h1>
<form>
  <div class="form-row">
    <div class="form-group col-md-2">
      <label for="nombre">Nombre</label>
      <input type="text" class="form-control" id="nombre" placeholder="Nombre Perfil" value="<%=@profile.nombre%>" readonly>
    </div>
    <div class="form-group col-md-2">
      <label for="apellido">Apellido</label>
      <input type="text" class="form-control" id="apellido" placeholder="Apellido Perfil" value="<%=@profile.apellido%>" readonly>
    </div>
    <div class="form-group col-md-3">
      <label for="inputEmail4">Email</label>
      <input type="email" class="form-control" id="inputEmail4" placeholder="Email" value="<%=@profile.email%>" readonly>
    </div>
    <div class="form-group col-md-2">
      <label for="dni">DNI</label>
      <input type="integer" class="form-control" id="dni" placeholder="Dni Perfil" value="<%=@profile.dni%>" readonly>
    </div>
  </div>
  <%=link_to "Editar Perfil", edit_profile_path(@profile), {class: "btn btn-info"}%>
</form>




<br>
<br>
<br>
<%= label_tag 'perros_label', 'Perros:', style: 'font-size: 30px;' %>
<div>  
  <%= link_to new_dog_path, { remote: true, class: "btn btn-info" }  do %>
    <span class="fas fa-plus-square" ></span>
  <% end %>
    <%= link_to "Cargar Vacunas", new_vacuna_path, html_options = {class: "btn btn-info btn-xs", remote: true} %>
    <%= link_to "Cargar Chequeos", new_chequeo_path, html_options = {class: "btn btn-info btn-xs", remote: true} %>
</div>
<br>
<div class="card shadow mb-4">
<div class="card-body">
    <div class="table-responsive">
    <table class="table table-bordered" id="tablaPerros" width="100%" cellspacing="0">
        <thead>
        <tr>
            <th>Nombre</th>
            <th>Sexo</th>
            <th>Raza</th>
            <th>Color</th>
            <th>Edad</th>
            <th>Peso(Kg)</th>
        </tr>
        </thead>
        <tbody>
            <% current_user.dog.all.each do |d| %>
            <tr id="perro_<%= d.id %>" >
                <td><%= d.nombre %></td>
                <td><%= d.sexo %></td>
                <td><%= d.raza %></td>
                <td><%= d.color %></td>
                <td><%= d.edad %></td>
                <td><%= d.peso %></td>
                <td>
                  <%= link_to "ver ficha medica", verFichaMedica_dog_path(d), html_options = {class: "btn btn-info btn-xs", remote: true} %>
                  
                </td>
              </tr>
            <% end %>
        </tbody>
    </table>
    </div>
  </div>
</div>

app/views/profiles/update.html.erb
<h1>Profiles#update</h1>
<p>Find me in app/views/profiles/update.html.erb</p>