config/routes.rb
Rails.application.routes.draw do
  
  resources :chequeos
  resources :vacunas
  patch '/profiles/:id/edit', to: 'profiles#update'  # Cambié 'profiles/:id' a '/profiles/:id'
  get '/profiles/:id/edit', to: 'profiles#edit', as: 'edit_profile'
  get '/profiles/:id', to: 'profiles#index', as: 'profile'
  get 'profiles/update'
  get 'inicio/index'
  get 'turnos/index'
  get 'authentication/sessions/new'
  resources :turnos
  resources :main
  namespace :authentication, path: '', as: '' do
    resources :users, only: [:new, :create]
    resources :sessions, only: [:new, :create]
  end
  get 'logout', to: 'authentication/sessions#destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "inicio#index"
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :profiles, only: [:index, :edit, :update]
  resources :dogs
  resources :dogs do
    get 'verFichaMedica', on: :member
  end
  
end

app/models/chequeo.rb
class Chequeo < ApplicationRecord
    belongs_to :dog
    validates :descripcion, presence: true
    validates :fecha, presence: true

    validate :datetime_not_in_future
    
    validate :chequeo_no_duplicado
    
    private
    def datetime_not_in_future
        if fecha? && fecha > Time.now
          errors.add(:fecha, "no debe ser futura")
        end
    end

    def chequeo_no_duplicado
      if Chequeo.exists?(fecha: self.fecha, descripcion: self.descripcion)
        errors.add(:base, "Chequeo ya cargado")
      end
    end

end

app/controllers/chequeos_controller.rb
class ChequeosController < ApplicationController
  before_action :set_chequeo, only: %i[ show edit update destroy ]

  # GET /chequeos or /chequeos.json
  def index
    @chequeos = Chequeo.all
  end

  # GET /chequeos/1 or /chequeos/1.json
  def show
  end

  # GET /chequeos/new
  def new
    @chequeo = Chequeo.new
  end

  # GET /chequeos/1/edit
  def edit
  end

  # POST /chequeos or /chequeos.json
  def create
    @chequeo = Chequeo.new(chequeo_params)
    @dog = current_user.dog.find(params[:chequeo][:dog_id]) # Asegúrate de que :dog_id esté presente en params
    @chequeo.dog = @dog
    
    respond_to do |format|
      if @chequeo.save
        format.html { redirect_to "/profiles/index" }
        format.json { render :show, status: :created, location: @chequeo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @chequeo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chequeos/1 or /chequeos/1.json
  def update
    respond_to do |format|
      if @chequeo.update(chequeo_params)
        format.html { redirect_to chequeo_url(@chequeo), notice: "Chequeo was successfully updated." }
        format.json { render :show, status: :ok, location: @chequeo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @chequeo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chequeos/1 or /chequeos/1.json
  def destroy
    @chequeo.destroy!

    respond_to do |format|
      format.html { redirect_to chequeos_url, notice: "Chequeo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chequeo
      @chequeo = Chequeo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def chequeo_params
      params.require(:chequeo).permit(:descripcion, :fecha)
    end
end

app/helpers/chequeos_helper.rb
module ChequeosHelper
end

app/views/chequeos/_chequeo.html.erb
<div id="<%= dom_id chequeo %>">
  <p>
    <strong>Descripcion:</strong>
    <%= chequeo.descripcion %>
  </p>

  <p>
    <strong>Fecha:</strong>
    <%= chequeo.fecha %>
  </p>

</div>

app/views/chequeos/_form.html.erb
<%= form_with(model: chequeo) do |form| %>
  <% if chequeo.errors.any? %>
    <div style="color: red">
     
      <ul>
        <% chequeo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :dog_id, "Perro" %>
    <%= form.collection_select(:dog_id, current_user.dog.all, :id, :nombre, prompt: "Selecciona un perro") %>
  </div>

  <div>
    <%= form.label :descripcion, style: "display: block" %>
    <%= form.text_field :descripcion %>
  </div>

  <div>
    <%= form.label :fecha, style: "display: block" %>
    <%= form.date_field :fecha %>
  </div>

  <div>
    <%= form.submit "cargar chequeo" %>
  </div>
<% end %>

app/views/chequeos/edit.html.erb
<h1>Editing chequeo</h1>

<%= render "form", chequeo: @chequeo %>

<br>

<div>
  <%= link_to "Show this chequeo", @chequeo %> |
  <%= link_to "Back to chequeos", chequeos_path %>
</div>

app/views/chequeos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Chequeos</h1>

<div id="chequeos">
  <% @chequeos.each do |chequeo| %>
    <%= render chequeo %>
    <p>
      <%= link_to "Show this chequeo", chequeo %>
    </p>
  <% end %>
</div>

<%= link_to "New chequeo", new_chequeo_path %>

app/views/chequeos/new.html.erb
<h1>New chequeo</h1>

<%= render "form", chequeo: @chequeo %>

<br>

<div>
  <%= link_to "Volver", "/profiles/index" %>
</div>

app/views/chequeos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @chequeo %>

<div>
  <%= link_to "Edit this chequeo", edit_chequeo_path(@chequeo) %> |
  <%= link_to "Back to chequeos", chequeos_path %>

  <%= button_to "Destroy this chequeo", @chequeo, method: :delete %>
</div>