config/routes.rb
Rails.application.routes.draw do
  
  resources :chequeos
  resources :vacunas
  patch '/profiles/:id/edit', to: 'profiles#update'  # Cambié 'profiles/:id' a '/profiles/:id'
  get '/profiles/:id/edit', to: 'profiles#edit', as: 'edit_profile'
  get '/profiles/:id', to: 'profiles#index', as: 'profile'
  get 'profiles/update'
  get 'inicio/index'
  get 'turnos/index'
  get 'authentication/sessions/new'
  resources :turnos
  resources :main
  namespace :authentication, path: '', as: '' do
    resources :users, only: [:new, :create]
    resources :sessions, only: [:new, :create]
  end
  get 'logout', to: 'authentication/sessions#destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "inicio#index"
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :profiles, only: [:index, :edit, :update]
  resources :dogs
  resources :dogs do
    get 'verFichaMedica', on: :member
  end
  
end

app/models/vacuna.rb
class Vacuna < ApplicationRecord
    belongs_to :dog
    validates :nombre, presence: true
    validates :fecha, presence: true


    validate :datetime_not_in_future
    
    validate :vacuna_no_duplicada

    private
  def datetime_not_in_future
    if fecha? && fecha > Time.now
      errors.add(:fecha, "no debe ser futura")
    end
  end

  def vacuna_no_duplicada
    if current_user.dog.chequeo.exists?(fecha: self.fecha, nombre: self.nombre)
      errors.add(:base, "Vacuna ya cargada")
    end
  end

end

app/controllers/vacunas_controller.rb
class VacunasController < ApplicationController
  before_action :set_vacuna, only: %i[ show edit update destroy ]

  # GET /vacunas or /vacunas.json
  def index
    @vacunas = Vacuna.all
  end

  # GET /vacunas/1 or /vacunas/1.json
  def show
  end

  # GET /vacunas/new
  def new
    @vacuna = Vacuna.new
    
  end

  # GET /vacunas/1/edit
  def edit
  end

  # POST /vacunas or /vacunas.json
  def create
    @vacuna = Vacuna.new(vacuna_params)
   
    @dog = current_user.dog.find(params[:vacuna][:dog_id]) # Asegúrate de que :dog_id esté presente en params
  @vacuna.dog = @dog

    respond_to do |format|
      if @vacuna.save
        format.html { redirect_to "/profiles/index"}
        format.json { render :show, status: :created, location: @vacuna }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vacuna.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vacunas/1 or /vacunas/1.json
  def update
    respond_to do |format|
      if @vacuna.update(vacuna_params)
        format.html { redirect_to vacuna_url(@vacuna), notice: "Vacuna was successfully updated." }
        format.json { render :show, status: :ok, location: @vacuna }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vacuna.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vacunas/1 or /vacunas/1.json
  def destroy
    @vacuna.destroy!

    respond_to do |format|
      format.html { redirect_to vacunas_url, notice: "Vacuna was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vacuna
      @vacuna = Vacuna.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vacuna_params
      params.require(:vacuna).permit(:nombre,:dog_id, :fecha)
    end
end

app/helpers/vacunas_helper.rb
module VacunasHelper
end

app/views/vacunas/_form.html.erb
<%= form_with(model: vacuna) do |form| %>
  <% if vacuna.errors.any? %>
    <div style="color: red">
      <ul>
        <% vacuna.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

   <div>
    <%= form.label :dog_id, "Perro" %>
    <%= form.collection_select(:dog_id, current_user.dog.all, :id, :nombre, prompt: "Selecciona un perro") %>
  </div>

  <div>
    <%= form.label :nombre, style: "display: block" %>
    <%= form.text_field :nombre %>
  </div>

  <div>
    <%= form.label :fecha, style: "display: block" %>
    <%= form.date_field :fecha %>
  </div>
  
  <div>
    <%= form.submit "Cargar vacuna" %>
  </div>
<% end %>

app/views/vacunas/_vacuna.html.erb
<div id="<%= dom_id vacuna %>">
  <p>
    <strong>Nombre:</strong>
    <%= vacuna.nombre %>
  </p>

  <p>
    <strong>Fecha:</strong>
    <%= vacuna.fecha %>
  </p>

</div>

app/views/vacunas/edit.html.erb
<h1>Editing vacuna</h1>

<%= render "form", vacuna: @vacuna %>

<br>

<div>
  <%= link_to "Show this vacuna", @vacuna %> |
  <%= link_to "Back to vacunas", vacunas_path %>
</div>

app/views/vacunas/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Vacunas</h1>

<div id="vacunas">
  <% @vacunas.each do |vacuna| %>
    <%= render vacuna %>
    <p>
      <%= link_to "Show this vacuna", vacuna %>
    </p>
  <% end %>
</div>

<%= link_to "New vacuna", new_vacuna_path %>

app/views/vacunas/new.html.erb
<h1>Cargar vacuna</h1>

<%= render "form", vacuna: @vacuna %>

<br>

<div>
  <%= link_to "Volver", "/profiles/index" %>
</div>

app/views/vacunas/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @vacuna %>

<div>
  <%= link_to "Edit this vacuna", edit_vacuna_path(@vacuna) %> |
  <%= link_to "Back to vacunas", vacunas_path %>

  <%= button_to "Destroy this vacuna", @vacuna, method: :delete %>
</div>